### PR TITLE
chore: migrate instructions

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

VSCode apparently re-arranges some properties, but what this PR *actually* does is two-fold.

- It adds numeration to the cells, such as `# 3`, to coincide with the instructions on `/learn`.
- It removes the instructions from the notebook.

### CODE REVIEW

**Comment by RandellDawson** [comment]
@naomi-lgbt After merging PR #2, some of the instructions may need changing on `/learn` in addition to fixing the merge conflict on this PR.

**Comment by naomi-lgbt** [comment]
Thanks for the heads up Randy! I've created https://github.com/freeCodeCamp/freeCodeCamp/pull/47130 to resolve the typos, and given this a rebase.

**Review by RandellDawson — APPROVED** [review]
LGTM  Since the instructions are already on production `/learn` with the exception of the typos from the latest PR merged, I think we can go ahead and merge this one once it gets a second approval.

**Review by Sboonny — COMMENTED** [review]
I have no idea, how does the block use Jupyter Notebook, I have to move the review to tom.

**Comment by gikf** [comment]
Github is still complaining about missing metadata https://github.com/freeCodeCamp/boilerplate-cat-and-dog-image-classifier/blob/chore/remove-instructions/fcc_cat_dog.ipynb
> Invalid notebook
data.metadata.language_info must contain ['name'] properties

But I guess it doesn't matter that much, since colab works fine with it.

**Review by gikf — APPROVED** [review]

**Pull request merged**
